#!/usr/bin/env bash
# generate-backpressure.sh — scan the project and emit a customized
# scripts/kessel-run/backpressure.sh with only the checks that apply,
# locked in (no runtime probing), using the detected package manager.
#
# Usage (run from project root):
#   bash /path/to/kessel-run/scripts/generate-backpressure.sh
#   bash /path/to/kessel-run/scripts/generate-backpressure.sh --stdout  # preview only
#   bash /path/to/kessel-run/scripts/generate-backpressure.sh --preset careatlas
set -euo pipefail

STDOUT_ONLY=false
PRESET=""
OUT_PATH="scripts/kessel-run/backpressure.sh"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --stdout)      STDOUT_ONLY=true; shift ;;
        --preset)      PRESET="$2"; shift 2 ;;
        --preset=*)    PRESET="${1#*=}"; shift ;;
        --out)         OUT_PATH="$2"; shift 2 ;;
        -h|--help)     sed -n '2,10p' "$0"; exit 0 ;;
        *)             echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

# ── Detect package manager ────────────────────────────────────────
PM="npx"  # default — works for most Node checks
PM_RUN="npx"
if [ -f pnpm-lock.yaml ]; then
    PM="pnpm"; PM_RUN="pnpm"
elif [ -f yarn.lock ]; then
    PM="yarn"; PM_RUN="yarn"
elif [ -f bun.lockb ] || [ -f bun.lock ]; then
    PM="bun"; PM_RUN="bun"
elif [ -f package-lock.json ]; then
    PM="npm"; PM_RUN="npx"
fi

# ── Detect which checks apply ─────────────────────────────────────
CHECKS=()

PACKAGE_SCRIPTS=""
if [ -f package.json ]; then
    PACKAGE_SCRIPTS=$(jq -r '.scripts // {} | keys[]' package.json 2>/dev/null || true)
fi
has_script() {
    printf '%s\n' "$PACKAGE_SCRIPTS" | grep -qx "$1"
}

# TypeScript
if [ -f tsconfig.json ]; then
    if has_script "typecheck"; then
        CHECKS+=("tsc|$PM_RUN run typecheck")
    elif has_script "tsc"; then
        CHECKS+=("tsc|$PM_RUN run tsc")
    else
        CHECKS+=("tsc|npx tsc --noEmit")
    fi
fi

# Lint
if [ -f eslint.config.mjs ] || [ -f eslint.config.js ] || [ -f .eslintrc.json ] || [ -f .eslintrc.js ]; then
    if has_script "lint"; then
        CHECKS+=("lint|$PM_RUN run lint")
    else
        CHECKS+=("lint|npx eslint . --max-warnings 0")
    fi
fi

# Test (vitest/jest)
if [ -f vitest.config.ts ] || [ -f vitest.config.mts ] || [ -f vitest.config.js ]; then
    if has_script "test"; then
        CHECKS+=("vitest|$PM_RUN run test -- --run")
    else
        CHECKS+=("vitest|npx vitest run")
    fi
elif [ -f jest.config.js ] || [ -f jest.config.ts ] || [ -f jest.config.mjs ]; then
    if has_script "test"; then
        CHECKS+=("jest|$PM_RUN run test")
    else
        CHECKS+=("jest|npx jest")
    fi
fi

# Next.js build
if [ -f next.config.ts ] || [ -f next.config.mjs ] || [ -f next.config.js ]; then
    if has_script "build"; then
        CHECKS+=("next-build|$PM_RUN run build")
    else
        CHECKS+=("next-build|npx next build")
    fi
fi

# Convex
if [ -d convex ]; then
    CHECKS+=("convex|npx convex typecheck")
fi

# Playwright E2E
if [ -f playwright.config.ts ] || [ -f playwright.config.js ]; then
    if ls tests/*.spec.ts tests/*.spec.js e2e/*.spec.ts e2e/*.spec.js 2>/dev/null | head -1 >/dev/null 2>&1; then
        CHECKS+=("playwright|npx playwright test")
    fi
fi

# Cypress
if [ -f cypress.config.ts ] || [ -f cypress.config.js ]; then
    CHECKS+=("cypress|npx cypress run")
fi

# Python
if [ -f pyproject.toml ]; then
    if [ -d tests ] || [ -d test ]; then
        CHECKS+=("pytest|python -m pytest")
    fi
fi

# Rust
if [ -f Cargo.toml ]; then
    CHECKS+=("cargo-test|cargo test")
    CHECKS+=("cargo-clippy|cargo clippy -- -D warnings")
fi

# Go
if [ -f go.mod ]; then
    CHECKS+=("go-build|go build ./...")
    CHECKS+=("go-test|go test ./...")
fi

# ── Preset overrides ──────────────────────────────────────────────
case "$PRESET" in
    careatlas)
        # Force pnpm + convex + known CareAtlas scripts
        CHECKS=()
        [ -f tsconfig.json ] && CHECKS+=("tsc|pnpm typecheck")
        CHECKS+=("lint|pnpm lint")
        CHECKS+=("test|pnpm test")
        CHECKS+=("build|pnpm build")
        [ -d convex ] && CHECKS+=("convex|npx convex typecheck")
        ;;
    "")
        ;;
    *)
        echo "Unknown preset: $PRESET" >&2; exit 1 ;;
esac

[ "${#CHECKS[@]}" -eq 0 ] && { echo "No checks detected — add at least one config file" >&2; exit 1; }

# ── Emit backpressure.sh ──────────────────────────────────────────
emit() {
    cat <<'HEADER'
#!/usr/bin/env bash
# Deflector shields — quality gate. Exit 0 = green, non-zero = red.
# Generated by kessel-run/scripts/generate-backpressure.sh — do not hand-edit
# if you plan to regenerate. Add custom checks to the "Custom" section below.
set -euo pipefail
FAILURES="" ; EXIT_CODE=0

check() {
  local name="$1"; shift
  local output
  printf "  ▸ %s ... " "$name"
  if output=$("$@" 2>&1); then
    echo "PASS"
    return 0
  fi
  echo "FAIL"
  FAILURES+=$'\n'"--- FAIL: $name ---"$'\n'"$(echo "$output" | tail -40)"$'\n'
  EXIT_CODE=1
}

HEADER

    echo "# ── Stack-detected checks ─────────────────────────────────────"
    for entry in "${CHECKS[@]}"; do
        name="${entry%%|*}"
        cmd="${entry#*|}"
        printf 'check "%s" %s\n' "$name" "$cmd"
    done

    cat <<'FOOTER'

# ── Custom (add your own below) ─────────────────────────────────────
# check "my-custom-gate" ./scripts/my-gate.sh

# ── Report ──────────────────────────────────────────────────────────
if [ $EXIT_CODE -eq 0 ]; then
    echo ""
    echo "✓ ALL GREEN"
else
    echo ""
    echo "━━━ FAILURES ━━━"
    echo "$FAILURES" | head -120
fi
exit $EXIT_CODE
FOOTER
}

if [ "$STDOUT_ONLY" = true ]; then
    emit
else
    mkdir -p "$(dirname "$OUT_PATH")"
    emit > "$OUT_PATH"
    chmod +x "$OUT_PATH"
    echo "✓ Wrote $OUT_PATH"
    echo ""
    echo "Detected checks:"
    for entry in "${CHECKS[@]}"; do
        printf "  • %-15s → %s\n" "${entry%%|*}" "${entry#*|}"
    done
    [ -n "$PRESET" ] && echo "" && echo "Preset: $PRESET"
fi
